-- 코드를 입력하세요
SELECT o.ANIMAL_ID, o.NAME
from ANIMAL_OUTS o
left join ANIMAL_INS i
on i.ANIMAL_ID = o.ANIMAL_ID
where i.DATETIME is null
order by o.ANIMAL_ID

 

# SELECT A.ANIMAL_ID, A.NAME
# FROM ANIMAL_OUTS A 
# LEFT JOIN ANIMAL_INS B 
# ON A.ANIMAL_ID = B.ANIMAL_ID
# WHERE B.ANIMAL_ID IS NULL
# ORDER BY A.ANIMAL_ID
