select b.WRITER_ID as USER_ID, u.NICKNAME as NICKNAME, SUM(PRICE) as TOTAL_SALES
from USED_GOODS_BOARD b
join USED_GOODS_USER u on b.WRITER_ID = u.USER_ID
where STATUS = 'DONE' 
# and SUM(PRICE)>= 7000000
group by WRITER_ID
having  SUM(PRICE)>= 700000
order by 3